import { Inter } from "next/font/google";
import { UserProvider } from "@/hooks/userContext";
import "../sass/global.scss";
import "../sass/fonts/fonts.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang="en" className={inter.className}>
        <body>
          <main className="main">{children}</main>
        </body>
      </html>
    </UserProvider>
  );
}
